name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch: # Allows manual runs

jobs:
  stale:
    runs-on: ubuntu-latest
    # https://github.com/actions/stale
    permissions:
      contents: write # only for delete-branch option
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
